In [309]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [310]:
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

In [311]:
iris = load_iris()
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [312]:
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target, columns=['species'])
df = pd.concat([X,y], axis=1)

In [313]:
df = df[df['species']!=2]

In [314]:
X = df[iris.feature_names]
y = df.species

In [315]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(np.array(X_train)[:,3])
X_train.head()

[1.3 0.4 0.2 0.4 0.2 0.4 1.3 0.2 0.2 1.6 1.  0.2 0.2 0.1 1.5 0.2 0.2 1.3
 1.1 0.2 0.2 1.4 0.3 0.2 1.3 0.2 0.2 1.3 1.5 0.2 0.2 1.  0.3 1.  1.5 0.2
 1.5 0.3 0.2 0.2 1.4 0.2 1.  1.3 1.2 0.1 0.2 1.5 1.7 0.2 1.4 1.4 0.3 1.5
 1.4 0.2 1.  0.4 0.4 1.4 1.3 1.5 1.5 1.  0.1 0.5 0.2 0.2 1.2 1.8]


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
58                6.6               2.9                4.6               1.3
15                5.7               4.4                1.5               0.4
8                 4.4               2.9                1.4               0.2
44                5.1               3.8                1.9               0.4
11                4.8               3.4                1.6               0.2

In [316]:
def sigmoid(X, theta):
    z = np.dot(X, theta[1:]) + theta[0]
    return 1.0 / ( 1.0 + np.exp(-z))

In [317]:
def LRFunction(y, hx):
    func = -y.dot(np.log(hx)) - ((1 - y).dot(np.log(1-hx)))
    return func

In [318]:
def LRGradient(X, y, theta, alpha, num_iter):
    for i in range(num_iter):
        hx = sigmoid(X, theta)
        error = hx - y
        grad = X.T.dot(error)
        theta[0] = theta[0] - alpha * error.sum()
        theta[1:] = theta[1:] - alpha * grad
        cost.append(LRFunction(y, hx))       

In [319]:
m, n = X_train.shape
theta = np.zeros(1+n)
alpha = 0.01
num_iter = 500
LRGradient(X_train, y_train, theta, alpha, num_iter)

In [320]:
def lrPredict(X):
    return np.where(sigmoid(X,theta) >= 0.5, 1, 0)
lrPredict(X_test)

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0])

In [321]:
reg = LogisticRegression()
reg.fit(X_train,y_train)
reg.predict(X_test)

c:\users\сергей\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0])

In [322]:
m, n = X_train.shape
theta = np.zeros(1+n)
alpha = 0.01
num_iter = 500
impuls = np.zeros(1+n)
gamma = 0.9

In [341]:
def LRNesterov(X, y, theta, impuls, alpha, gamma, num_iter):
    for i in range(num_iter):
        hx = sigmoid((X+gamma*impuls[1:]), theta)
        error = hx - y
        grad = (X+gamma*impuls[1:]).T.dot(error)
        impuls[0] = gamma*impuls[0] - alpha * (1 - gamma) * error.sum()
        impuls[1:] = gamma*impuls[1:] - alpha * (1 - gamma) * grad
        theta = theta + impuls

In [342]:
LRNesterov(X_train, y_train, theta, impuls, alpha, gamma, num_iter)
lrPredict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])